

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    honor_labels: true
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['localhost:9090']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'prometheus'

  - job_name: 'node-exporter'
    honor_labels: true
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'node-exporter'

  - job_name: 'validator-node'
    honor_labels: true
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['host.docker.internal:26660'] # Typical metrics port for Cosmos-based chains
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'validator-node'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(go_|process_).*'
        action: drop

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

